import type { ImportEntityType } from './types';

export const ENTITY_ORDER: ImportEntityType[] = [
  'client',
  'service',
  'project',
  'estimate',
  'contract',
  'invoice',
  'payment',
  'transaction',
  'event',
];

export const ENTITY_LABELS: Record<ImportEntityType, string> = {
  client: 'Cliente',
  service: 'Servizio',
  project: 'Progetto',
  estimate: 'Preventivo',
  contract: 'Contratto',
  invoice: 'Fattura',
  payment: 'Pagamento',
  transaction: 'Movimento',
  event: 'Evento',
};

export const ENTITY_GROUP_LABELS: Record<ImportEntityType, string> = {
  client: 'Clienti',
  service: 'Servizi',
  project: 'Progetti',
  estimate: 'Preventivi',
  contract: 'Contratti',
  invoice: 'Fatture',
  payment: 'Pagamenti',
  transaction: 'Movimenti',
  event: 'Eventi',
};

export const ENTITY_KEYWORDS: Record<ImportEntityType, string[]> = {
  client: ['cliente', 'client', 'azienda', 'ragione sociale', 'nome cliente', 'settore', 'partita iva', 'p iva'],
  project: ['progetto', 'project', 'nome progetto', 'scadenza', 'valore contrattuale', 'ore stimate'],
  estimate: ['preventivo', 'estimate', 'quote', 'numero preventivo', 'prev-', 'validita', 'totale', 'accettato'],
  contract: ['contratto', 'contract', 'numero contratto', 'data inizio', 'data fine'],
  invoice: ['fattura', 'invoice', 'fat-', 'data emissione', 'data scadenza'],
  payment: ['pagamento', 'payment', 'metodo', 'importo', 'rata', 'pagato', 'in attesa'],
  service: ['servizio', 'service', 'prezzo base', 'ore stimate', 'margine target'],
  event: ['evento', 'scadenza', 'meeting', 'riunione', 'data', 'orario'],
  transaction: ['movimento', 'entrata', 'uscita', 'transaction', 'spesa', 'ricavo'],
};

export const MONTHS_IT: Record<string, number> = {
  gennaio: 1,
  febbraio: 2,
  marzo: 3,
  aprile: 4,
  maggio: 5,
  giugno: 6,
  luglio: 7,
  agosto: 8,
  settembre: 9,
  ottobre: 10,
  novembre: 11,
  dicembre: 12,
};

export const CLIENT_STATUS_MAP: Record<string, string> = {
  lead: 'lead',
  prospect: 'prospect',
  attivo: 'active',
  attiva: 'active',
  active: 'active',
  inattivo: 'inactive',
  inactive: 'inactive',
  partner: 'partner',
  archiviato: 'archived',
  archived: 'archived',
  'ex cliente': 'past_client',
  'past client': 'past_client',
};

export const PROJECT_STATUS_MAP: Record<string, string> = {
  lead: 'lead',
  draft: 'draft',
  bozza: 'draft',
  planned: 'planned',
  pianificato: 'planned',
  pianificata: 'planned',
  active: 'active',
  attivo: 'active',
  attiva: 'active',
  'waiting client': 'waiting_client',
  'attesa cliente': 'waiting_client',
  review: 'review',
  revisione: 'review',
  paused: 'paused',
  pausa: 'paused',
  completed: 'completed',
  completato: 'completed',
  cancelled: 'cancelled',
  cancellato: 'cancelled',
  archived: 'archived',
  archiviato: 'archived',
};

export const ESTIMATE_STATUS_MAP: Record<string, string> = {
  draft: 'draft',
  bozza: 'draft',
  'internal review': 'internal_review',
  'revisione interna': 'internal_review',
  sent: 'sent',
  inviato: 'sent',
  inviata: 'sent',
  viewed: 'viewed',
  visto: 'viewed',
  visualizzato: 'viewed',
  accepted: 'accepted',
  accettato: 'accepted',
  accettata: 'accepted',
  rejected: 'rejected',
  rifiutato: 'rejected',
  expired: 'expired',
  scaduto: 'expired',
  cancelled: 'cancelled',
  annullato: 'cancelled',
  superseded: 'superseded',
};

export const CONTRACT_STATUS_MAP: Record<string, string> = {
  draft: 'draft',
  bozza: 'draft',
  sent: 'sent',
  inviato: 'sent',
  'awaiting signature': 'awaiting_signature',
  'attesa firma': 'awaiting_signature',
  active: 'active',
  attivo: 'active',
  'active maintenance': 'active',
  expired: 'expired',
  scaduto: 'expired',
  terminated: 'terminated',
  terminato: 'terminated',
  cancelled: 'cancelled',
  annullato: 'cancelled',
  archived: 'archived',
  archiviato: 'archived',
};

export const INVOICE_STATUS_MAP: Record<string, string> = {
  draft: 'draft',
  bozza: 'draft',
  issued: 'issued',
  emessa: 'issued',
  sent: 'sent',
  inviata: 'sent',
  viewed: 'viewed',
  vista: 'viewed',
  'partially paid': 'partially_paid',
  'parzialmente pagata': 'partially_paid',
  paid: 'paid',
  pagata: 'paid',
  overdue: 'overdue',
  scaduta: 'overdue',
  cancelled: 'cancelled',
  annullata: 'cancelled',
  credited: 'credited',
};

export const PAYMENT_STATUS_MAP: Record<string, string> = {
  pending: 'pending',
  'in attesa': 'pending',
  completed: 'completed',
  pagato: 'completed',
  pagata: 'completed',
  failed: 'failed',
  fallito: 'failed',
  refunded: 'refunded',
  rimborsato: 'refunded',
  cancelled: 'cancelled',
  annullato: 'cancelled',
};

export const PAYMENT_METHOD_MAP: Record<string, string> = {
  bonifico: 'bank_transfer',
  'bank transfer': 'bank_transfer',
  carta: 'card',
  card: 'card',
  paypal: 'paypal',
  stripe: 'stripe',
  contanti: 'cash',
  cash: 'cash',
  assegno: 'cheque',
  cheque: 'cheque',
  altro: 'other',
  other: 'other',
};

export const PRICE_UNIT_MAP: Record<string, string> = {
  fisso: 'fixed',
  fixed: 'fixed',
  orario: 'hourly',
  hourly: 'hourly',
  giornaliero: 'daily',
  daily: 'daily',
  mensile: 'monthly',
  monthly: 'monthly',
  quantita: 'quantity',
  quantity: 'quantity',
  custom: 'custom',
};

export const PRIORITY_MAP: Record<string, string> = {
  bassa: 'low',
  low: 'low',
  media: 'medium',
  medium: 'medium',
  alta: 'high',
  high: 'high',
  urgente: 'urgent',
  urgent: 'urgent',
};

export const EVENT_TYPE_MAP: Record<string, string> = {
  evento: 'custom',
  custom: 'custom',
  meeting: 'meeting',
  riunione: 'meeting',
  'client call': 'client_call',
  'chiamata cliente': 'client_call',
  'estimate due': 'estimate_due',
  'scadenza preventivo': 'estimate_due',
  'invoice due': 'invoice_due',
  'scadenza fattura': 'invoice_due',
  'payment due': 'payment_due',
  'scadenza pagamento': 'payment_due',
  'project deadline': 'project_deadline',
  'scadenza progetto': 'project_deadline',
  ferie: 'time_off',
  'time off': 'time_off',
};
